import type { PlanConfig } from '@/app/pricing/PricingCards'

export const PLANS: PlanConfig[] = [
  {
    name: 'Free',
    tier: 'free',
    monthlyPrice: '$0',
    annualPrice: '$0',
    annualMonthly: '$0',
    description: 'Try it out',
    searches: '3 searches / month',
    features: ['AI analysis', 'Photo match evidence', 'Client management'],
    monthlyPriceId: null,
    annualPriceId: null,
  },
  {
    name: 'Starter',
    tier: 'starter',
    monthlyPrice: '$50',
    annualPrice: '$480',
    annualMonthly: '$40',
    description: 'For growing agents',
    searches: '20 searches / month',
    features: [
      'Everything in Free',
      '30 listings analyzed per search',
      'Reports',
      'Email support',
    ],
    monthlyPriceId: process.env.STRIPE_PRICE_STARTER ?? null,
    annualPriceId: process.env.STRIPE_PRICE_STARTER_ANNUAL ?? null,
  },
  {
    name: 'Pro',
    tier: 'pro',
    monthlyPrice: '$150',
    annualPrice: '$1,440',
    annualMonthly: '$120',
    description: 'For full-time agents',
    searches: '60 searches / month',
    features: [
      'Everything in Starter',
      '40 listings analyzed per search',
      'Priority support',
      'Early access to features',
    ],
    monthlyPriceId: process.env.STRIPE_PRICE_PRO ?? null,
    annualPriceId: process.env.STRIPE_PRICE_PRO_ANNUAL ?? null,
  },
  {
    name: 'Premier',
    tier: 'premier',
    monthlyPrice: '$400',
    annualPrice: '$3,840',
    annualMonthly: '$320',
    description: 'For top producers & teams',
    searches: '150 searches / month',
    features: [
      'Everything in Pro',
      '50 listings analyzed per search',
      'Highest-priority queue',
    ],
    monthlyPriceId: process.env.STRIPE_PRICE_PREMIER ?? null,
    annualPriceId: process.env.STRIPE_PRICE_PREMIER_ANNUAL ?? null,
  },
]
